using System;
using System.Collections.Generic;

namespace ACEAPI.DatapointModels
{
    public partial class DboNameFlexData101To200
    {
        public short? InstitutionNumber { get; set; }
        public decimal? AccountNumber { get; set; }
        public byte? Application { get; set; }
        public short? RecordNumber { get; set; }
        public string Flex101Description { get; set; }
        public string Flex101 { get; set; }
        public string Flex102Description { get; set; }
        public string Flex102 { get; set; }
        public string Flex103Description { get; set; }
        public string Flex103 { get; set; }
        public string Flex104Description { get; set; }
        public string Flex104 { get; set; }
        public string Flex105Description { get; set; }
        public string Flex105 { get; set; }
        public string Flex106Description { get; set; }
        public string Flex106 { get; set; }
        public string Flex107Description { get; set; }
        public string Flex107 { get; set; }
        public string Flex108Description { get; set; }
        public string Flex108 { get; set; }
        public string Flex109Description { get; set; }
        public string Flex109 { get; set; }
        public string Flex110Description { get; set; }
        public string Flex110 { get; set; }
        public string Flex111Description { get; set; }
        public string Flex111 { get; set; }
        public string Flex112Description { get; set; }
        public string Flex112 { get; set; }
        public string Flex113Description { get; set; }
        public string Flex113 { get; set; }
        public string Flex114Description { get; set; }
        public string Flex114 { get; set; }
        public string Flex115Description { get; set; }
        public string Flex115 { get; set; }
        public string Flex116Description { get; set; }
        public string Flex116 { get; set; }
        public string Flex117Description { get; set; }
        public string Flex117 { get; set; }
        public string Flex118Description { get; set; }
        public string Flex118 { get; set; }
        public string Flex119Description { get; set; }
        public string Flex119 { get; set; }
        public string Flex120Description { get; set; }
        public string Flex120 { get; set; }
        public string Flex121Description { get; set; }
        public string Flex121 { get; set; }
        public string Flex122Description { get; set; }
        public string Flex122 { get; set; }
        public string Flex123Description { get; set; }
        public string Flex123 { get; set; }
        public string Flex124Description { get; set; }
        public string Flex124 { get; set; }
        public string Flex125Description { get; set; }
        public string Flex125 { get; set; }
        public string Flex126Description { get; set; }
        public string Flex126 { get; set; }
        public string Flex127Description { get; set; }
        public string Flex127 { get; set; }
        public string Flex128Description { get; set; }
        public string Flex128 { get; set; }
        public string Flex129Description { get; set; }
        public string Flex129 { get; set; }
        public string Flex130Description { get; set; }
        public string Flex130 { get; set; }
        public string Flex131Description { get; set; }
        public string Flex131 { get; set; }
        public string Flex132Description { get; set; }
        public string Flex132 { get; set; }
        public string Flex133Description { get; set; }
        public string Flex133 { get; set; }
        public string Flex134Description { get; set; }
        public string Flex134 { get; set; }
        public string Flex135Description { get; set; }
        public string Flex135 { get; set; }
        public string Flex136Description { get; set; }
        public string Flex136 { get; set; }
        public string Flex137Description { get; set; }
        public string Flex137 { get; set; }
        public string Flex138Description { get; set; }
        public string Flex138 { get; set; }
        public string Flex139Description { get; set; }
        public string Flex139 { get; set; }
        public string Flex140Description { get; set; }
        public string Flex140 { get; set; }
        public string Flex141Description { get; set; }
        public string Flex141 { get; set; }
        public string Flex142Description { get; set; }
        public string Flex142 { get; set; }
        public string Flex143Description { get; set; }
        public string Flex143 { get; set; }
        public string Flex144Description { get; set; }
        public string Flex144 { get; set; }
        public string Flex145Description { get; set; }
        public string Flex145 { get; set; }
        public string Flex146Description { get; set; }
        public string Flex146 { get; set; }
        public string Flex147Description { get; set; }
        public string Flex147 { get; set; }
        public string Flex148Description { get; set; }
        public string Flex148 { get; set; }
        public string Flex149Description { get; set; }
        public string Flex149 { get; set; }
        public string Flex150Description { get; set; }
        public string Flex150 { get; set; }
        public string Flex151Description { get; set; }
        public string Flex151 { get; set; }
        public string Flex152Description { get; set; }
        public string Flex152 { get; set; }
        public string Flex153Description { get; set; }
        public string Flex153 { get; set; }
        public string Flex154Description { get; set; }
        public string Flex154 { get; set; }
        public string Flex155Description { get; set; }
        public string Flex155 { get; set; }
        public string Flex156Description { get; set; }
        public string Flex156 { get; set; }
        public string Flex157Description { get; set; }
        public string Flex157 { get; set; }
        public string Flex158Description { get; set; }
        public string Flex158 { get; set; }
        public string Flex159Description { get; set; }
        public string Flex159 { get; set; }
        public string Flex160Description { get; set; }
        public string Flex160 { get; set; }
        public string Flex161Description { get; set; }
        public string Flex161 { get; set; }
        public string Flex162Description { get; set; }
        public string Flex162 { get; set; }
        public string Flex163Description { get; set; }
        public string Flex163 { get; set; }
        public string Flex164Description { get; set; }
        public string Flex164 { get; set; }
        public string Flex165Description { get; set; }
        public string Flex165 { get; set; }
        public string Flex166Description { get; set; }
        public string Flex166 { get; set; }
        public string Flex167Description { get; set; }
        public string Flex167 { get; set; }
        public string Flex168Description { get; set; }
        public string Flex168 { get; set; }
        public string Flex169Description { get; set; }
        public string Flex169 { get; set; }
        public string Flex170Description { get; set; }
        public string Flex170 { get; set; }
        public string Flex171Description { get; set; }
        public string Flex171 { get; set; }
        public string Flex172Description { get; set; }
        public string Flex172 { get; set; }
        public string Flex173Description { get; set; }
        public string Flex173 { get; set; }
        public string Flex174Description { get; set; }
        public string Flex174 { get; set; }
        public string Flex175Description { get; set; }
        public string Flex175 { get; set; }
        public string Flex176Description { get; set; }
        public string Flex176 { get; set; }
        public string Flex177Description { get; set; }
        public string Flex177 { get; set; }
        public string Flex178Description { get; set; }
        public string Flex178 { get; set; }
        public string Flex179Description { get; set; }
        public string Flex179 { get; set; }
        public string Flex180Description { get; set; }
        public string Flex180 { get; set; }
        public string Flex181Description { get; set; }
        public string Flex181 { get; set; }
        public string Flex182Description { get; set; }
        public string Flex182 { get; set; }
        public string Flex183Description { get; set; }
        public string Flex183 { get; set; }
        public string Flex184Description { get; set; }
        public string Flex184 { get; set; }
        public string Flex185Description { get; set; }
        public string Flex185 { get; set; }
        public string Flex186Description { get; set; }
        public string Flex186 { get; set; }
        public string Flex187Description { get; set; }
        public string Flex187 { get; set; }
        public string Flex188Description { get; set; }
        public string Flex188 { get; set; }
        public string Flex189Description { get; set; }
        public string Flex189 { get; set; }
        public string Flex190Description { get; set; }
        public string Flex190 { get; set; }
        public string Flex191Description { get; set; }
        public string Flex191 { get; set; }
        public string Flex192Description { get; set; }
        public string Flex192 { get; set; }
        public string Flex193Description { get; set; }
        public string Flex193 { get; set; }
        public string Flex194Description { get; set; }
        public string Flex194 { get; set; }
        public string Flex195Description { get; set; }
        public string Flex195 { get; set; }
        public string Flex196Description { get; set; }
        public string Flex196 { get; set; }
        public string Flex197Description { get; set; }
        public string Flex197 { get; set; }
        public string Flex198Description { get; set; }
        public string Flex198 { get; set; }
        public string Flex199Description { get; set; }
        public string Flex199 { get; set; }
        public string Flex200Description { get; set; }
        public string Flex200 { get; set; }
    }
}
